"""Static itinerary data for the Tokyo 2027 trip app.

Source of truth for prose content is ../itinerary.md — when the itinerary
changes there, update this file's DAYS list to match.
"""

DAYS = [
    {
        "day": 1,
        "date": "1/21（週四）",
        "title": "成田機場 → 河口湖",
        "status": "已確認",
        "items": [
            "兩批人機場集合：新竹團約06:00出發、台南團約04:00–04:30出發（草案，需與接送廠商核對）",
            "10:10 桃園機場起飛（JX802）",
            "14:20 抵達成田機場",
            "~15:20 入境/提行李完畢，包車出發前往河口湖（約2.5–3小時）",
            "~17:50–18:20 抵達湖山亭產屋 check-in",
            "晚上看富士山、泡湯；晚餐飯店內用",
        ],
    },
    {
        "day": 2,
        "date": "1/22（週五）",
        "title": "河口湖一日遊",
        "status": "已確認・彈性時間",
        "items": [
            "09:00 包車出發",
            "09:15–10:45 河口湖纜車（かちかち山ロープウェイ）+ 天上山公園",
            "11:00–12:15 忍野八海（含午餐：不動餺飥 或 天婦羅）",
            "12:35–13:40 新倉山淺間公園・忠靈塔",
            "13:50–14:20 日川鐘錶店拍照",
            "傍晚回飯店休息、泡湯；晚餐飯店內用",
        ],
    },
    {
        "day": 3,
        "date": "1/23（週六）",
        "title": "河口湖 → 富士サファリパーク → 東京上野",
        "status": "已確認",
        "items": [
            "~09:00 早餐、退房，包車出發",
            "車程約1hr抵達富士サファリパーク，遊園2.5–3hr",
            "車程約2hr前往東京，預計14:30–15:00抵達上野飯店 check-in",
            "晚上：飯店附近（阿美橫町）晚餐、稍微逛逛",
        ],
    },
    {
        "day": 4,
        "date": "1/24（週日）",
        "title": "豪德寺 + 秋葉原 + 貓頭鷹咖啡廳",
        "status": "草案・待確認",
        "transit": "🚇 上野→新宿（山手線）→豪德寺（小田急線）；新宿→秋葉原（中央・總武線快速）",
        "items": [
            "08:30 飯店早餐",
            "09:00 出發前往豪德寺（約40–45分）",
            "09:45–10:45 豪德寺（招財貓神社）參拜、拍照",
            "11:15–12:15 新宿午餐（候選：燒肉亭六歌仙／AFURI／百貨餐廳樓層／迴轉壽司）",
            "13:00–15:30 秋葉原逛街",
            "16:00–17:00 貓頭鷹咖啡廳アキバフクロウ（需線上預約）",
            "17:00起 秋葉原周邊或回上野晚餐",
        ],
    },
    {
        "day": 5,
        "date": "1/25（週一）",
        "title": "淺草 + 合羽橋 + 晴空塔",
        "status": "草案・待確認",
        "transit": "🚇 上野→淺草（銀座線，約10–15分）；淺草→晴空塔徒步可達",
        "items": [
            "配合大家不會太早出門，時間可彈性調整",
            "10:30–11:00 淺草寺、雷門",
            "11:00–12:00 仲見世通逛街",
            "12:00–13:00 淺草午餐",
            "13:15–14:15 合羽橋道具街（⚠️與隅田川水上巴士二選一）",
            "14:30–16:00 東京晴空塔展望台",
            "16:00–17:00 Solamachi逛街/午茶",
            "⚠️ 紅鶴舒芙蕾鬆餅早起排隊跟本日晚出發衝突，想吃需自己早起",
        ],
    },
    {
        "day": 6,
        "date": "1/26（週二）",
        "title": "東京迪士尼海洋",
        "status": "已確認",
        "transit": "🚇 上野→東京→舞浜（山手線+JR京葉線，約45分）",
        "items": [
            "平日（非六日），人潮通常比週末少",
            "建議07:30前到門口",
        ],
    },
    {
        "day": 7,
        "date": "1/27（週三）",
        "title": "豐洲市場 + teamLab + 澀谷 + Shibuya Sky",
        "status": "草案・待確認",
        "transit": "🚇 上野→豐洲（經新橋轉乘，約45–55分）；豐洲→澀谷（接山手線）",
        "items": [
            "⚠️ Shibuya Sky預約於入場日前28天日本時間00:00開放，1/27最快2026/12/30東京時間00:00搶票",
            "10:00–11:00 豐洲市場（⚠️公休日不固定需確認）",
            "11:00–11:30 千客萬来",
            "11:30–14:30 teamLab Planets TOKYO（⚠️需提前訂票，建議選較早時段）",
            "14:30–15:20 移動到澀谷",
            "15:20–16:00 澀谷Scramble Crossing、八公像",
            "16:00–16:30 Shibuya Sky（日落場次）",
            "⚠️ 明治神宮/原宿慢步路線尚未排入，待安插",
        ],
    },
    {
        "day": 8,
        "date": "1/28（週四）",
        "title": "上野公園散策 + 最後採購",
        "status": "草案・待確認",
        "items": [
            "09:00–10:30 上野公園寺廟散策（清水観音堂、上野東照宮、寛永寺）+ 湯島天神",
            "11:00–12:30 午餐：とん八亭（⚠️只有中午營業）",
            "13:00–17:00 阿美橫町／多慶屋 最後採購",
            "晚餐：上野周邊自由選",
        ],
    },
    {
        "day": 9,
        "date": "1/29（週五）",
        "title": "回台灣",
        "status": "已確認",
        "items": [
            "08:00 飯店早餐",
            "09:30–10:00 退房，行李裝車",
            "退房後直接前往成田機場，不安排其他行程",
            "~12:30–13:00 抵達成田機場，辦理報到/託運",
            "15:40 JX803 起飛／18:45 抵達台灣",
        ],
    },
]

# Confirmed itinerary locations for the map. Coordinates are approximate
# (city/landmark level), good enough for orientation — not survey-grade.
SPOTS = [
    {"name": "桃園機場", "day": 1, "category": "交通", "lat": 25.0777, "lon": 121.2325},
    {"name": "成田機場", "day": 1, "category": "交通", "lat": 35.7720, "lon": 140.3929},
    {"name": "湖山亭產屋（住宿）", "day": 1, "category": "住宿", "lat": 35.5010, "lon": 138.7520},
    {"name": "河口湖纜車／天上山公園", "day": 2, "category": "景點", "lat": 35.5075, "lon": 138.7720},
    {"name": "忍野八海", "day": 2, "category": "景點", "lat": 35.4520, "lon": 138.8280},
    {"name": "新倉山淺間公園・忠靈塔", "day": 2, "category": "景點", "lat": 35.4880, "lon": 138.8060},
    {"name": "日川時計店", "day": 2, "category": "景點", "lat": 35.4940, "lon": 138.8090},
    {"name": "富士サファリパーク", "day": 3, "category": "景點", "lat": 35.3096, "lon": 138.9377},
    {"name": "MONday Apart Premium 上野御徒町（住宿）", "day": 3, "category": "住宿", "lat": 35.7079, "lon": 139.7745},
    {"name": "豪德寺", "day": 4, "category": "景點", "lat": 35.6428, "lon": 139.6497},
    {"name": "新宿站", "day": 4, "category": "交通", "lat": 35.6896, "lon": 139.7006},
    {"name": "秋葉原", "day": 4, "category": "景點", "lat": 35.6984, "lon": 139.7731},
    {"name": "アキバフクロウ 貓頭鷹咖啡廳", "day": 4, "category": "景點", "lat": 35.6994, "lon": 139.7724},
    {"name": "淺草寺・雷門", "day": 5, "category": "景點", "lat": 35.7148, "lon": 139.7967},
    {"name": "仲見世通", "day": 5, "category": "景點", "lat": 35.7133, "lon": 139.7960},
    {"name": "合羽橋道具街", "day": 5, "category": "景點", "lat": 35.7128, "lon": 139.7900},
    {"name": "東京晴空塔", "day": 5, "category": "景點", "lat": 35.7101, "lon": 139.8107},
    {"name": "東京迪士尼海洋（舞浜）", "day": 6, "category": "景點", "lat": 35.6267, "lon": 139.8850},
    {"name": "豐洲市場", "day": 7, "category": "景點", "lat": 35.6455, "lon": 139.7828},
    {"name": "千客萬来", "day": 7, "category": "景點", "lat": 35.6461, "lon": 139.7838},
    {"name": "teamLab Planets TOKYO", "day": 7, "category": "景點", "lat": 35.6469, "lon": 139.7911},
    {"name": "澀谷 Scramble Crossing", "day": 7, "category": "景點", "lat": 35.6595, "lon": 139.7005},
    {"name": "Shibuya Sky", "day": 7, "category": "景點", "lat": 35.6580, "lon": 139.7016},
    {"name": "上野公園寺廟群", "day": 8, "category": "景點", "lat": 35.7156, "lon": 139.7745},
    {"name": "とん八亭", "day": 8, "category": "美食", "lat": 35.7075, "lon": 139.7739},
    {"name": "阿美橫町", "day": 8, "category": "景點", "lat": 35.7098, "lon": 139.7745},
]

# Candidate spots not yet placed into a fixed day (明治神宮/原宿 慢步路線 etc.)
CANDIDATE_SPOTS = [
    {"name": "明治神宮", "note": "原宿，尚未排入日期", "lat": 35.6764, "lon": 139.6993},
    {"name": "代代木公園", "note": "慢步休息候選", "lat": 35.6717, "lon": 139.6949},
    {"name": "東郷神社", "note": "慢步休息候選", "lat": 35.6716, "lon": 139.7025},
    {"name": "東京都廳展望室", "note": "Day4新宿順路候選，免費", "lat": 35.6896, "lon": 139.6917},
]

# 美食候選（可投票），source of truth 同步自 ../itinerary.md 的各餐廳候選清單
FOOD_CANDIDATES = [
    {"id": "f01", "area": "Day3 阿美橫町", "category": "鰻魚飯", "name": "名代宇奈とと", "desc": "平價鰻魚飯，外帶內用皆可，也有ひつまぶし"},
    {"id": "f02", "area": "Day3 阿美橫町", "category": "蕎麥麵", "name": "上野藪そば", "desc": "百年老店，阿美橫町一帶評價高"},
    {"id": "f03", "area": "Day3 阿美橫町", "category": "拉麵", "name": "蒙古タンメン中本", "desc": "招牌辣味噌拉麵"},
    {"id": "f04", "area": "Day3 阿美橫町", "category": "壽司", "name": "三浦三崎港", "desc": "迴轉壽司，食材大方"},
    {"id": "f05", "area": "Day3 阿美橫町", "category": "壽司", "name": "金沢まいもん寿司", "desc": "迴轉壽司"},
    {"id": "f06", "area": "Day3 阿美橫町", "category": "炸物/小吃", "name": "肉の大山", "desc": "可樂餅、炸肉餅，銅板價"},
    {"id": "f07", "area": "Day3 阿美橫町", "category": "炸物/小吃", "name": "山家", "desc": "豬排定食，約800–1200円"},
    {"id": "f08", "area": "Day3 阿美橫町", "category": "丼飯", "name": "伊勢ろく上野店", "desc": "親子丼"},
    {"id": "f09", "area": "Day3 阿美橫町", "category": "丼飯", "name": "天丼專賣店（穴子/星鰻）", "desc": "阿美橫町周邊有幾家專賣店"},
    {"id": "f10", "area": "Day3 阿美橫町", "category": "丼飯", "name": "阿美橫町鐵火丼", "desc": "海鮮丼類"},
    {"id": "f11", "area": "Day3 阿美橫町", "category": "居酒屋", "name": "塚田農場上野店", "desc": "雞肉料理為主，適合多人小酌配菜"},
    {"id": "f12", "area": "Day3 阿美橫町", "category": "居酒屋", "name": "文樂", "desc": "燒鳥/串燒，很熱門常客滿"},
    {"id": "f13", "area": "Day4 新宿", "category": "燒肉", "name": "燒肉亭 六歌仙 新宿店", "desc": "有吃到飽方案，適合11人聚餐"},
    {"id": "f14", "area": "Day4 新宿", "category": "拉麵", "name": "AFURI阿夫利 新宿店", "desc": "招牌柚子鹽拉麵，清爽系"},
    {"id": "f15", "area": "Day4 新宿", "category": "美食街", "name": "小田急/京王百貨餐廳樓層", "desc": "車站直通，選擇多"},
    {"id": "f16", "area": "Day4 新宿", "category": "壽司", "name": "西口迴轉壽司", "desc": "價格親民、翻桌快"},
    {"id": "f17", "area": "Day4 秋葉原", "category": "牛排", "name": "肉の万世 秋葉原本店", "desc": "老字號，份量足"},
    {"id": "f18", "area": "Day4 秋葉原", "category": "烤牛肉丼", "name": "ローストビーフ大野", "desc": "CP值高，翻桌快"},
    {"id": "f19", "area": "Day4 秋葉原", "category": "美食街", "name": "秋葉原UDX/ヨドバシAkiba", "desc": "大樓內多間餐廳"},
    {"id": "f20", "area": "Day5 淺草", "category": "天丼", "name": "雷門三定", "desc": "1837年創立，日本最古老天婦羅專賣店之一"},
    {"id": "f21", "area": "Day5 淺草", "category": "天丼", "name": "天麩羅秋光淺草本店", "desc": "五代目天丼，新鮮海鮮+當季蔬菜"},
    {"id": "f22", "area": "Day5 淺草", "category": "蕎麥麵", "name": "尾張屋", "desc": "150年老店，五代傳承"},
    {"id": "f23", "area": "Day5 淺草", "category": "壽喜燒", "name": "淺草今半", "desc": "百年老字號"},
    {"id": "f24", "area": "Day5 淺草", "category": "鰻魚飯", "name": "色川", "desc": "老字號鰻魚飯"},
    {"id": "f25", "area": "Day5 淺草", "category": "排隊小吃", "name": "淺草九重", "desc": "炸饅頭專賣店，多口味"},
    {"id": "f26", "area": "Day5 淺草", "category": "甜點", "name": "龜十", "desc": "東京三大銅鑼燒之一"},
    {"id": "f27", "area": "Day5 淺草", "category": "排隊小吃", "name": "淺草炸肉餅", "desc": "傳法院通，銅板價排隊美食"},
    {"id": "f28", "area": "Day5 淺草", "category": "鬆餅", "name": "紅鶴", "desc": "舒芙蕾鬆餅，需早起排整理券，與晚出發衝突"},
    {"id": "f29", "area": "Day7 澀谷/原宿", "category": "壽司", "name": "梅丘壽司美登利", "desc": "澀谷Mark City 4樓，食材每日從豐洲進貨"},
    {"id": "f30", "area": "Day7 澀谷/原宿", "category": "壽司", "name": "澀谷PARCO 7樓迴轉壽司", "desc": "CP值不輸美登利"},
    {"id": "f31", "area": "Day7 澀谷/原宿", "category": "拉麵", "name": "Hayashi", "desc": "澀谷在地人推薦，豬骨+海鮮高湯"},
    {"id": "f32", "area": "Day7 澀谷/原宿", "category": "拉麵", "name": "AFURI阿夫利（原宿）", "desc": "招牌柚子鹽拉麵"},
    {"id": "f33", "area": "Day7 澀谷/原宿", "category": "燒肉/肉類", "name": "澀谷肉橫丁", "desc": "肉主題美食街，多種選擇"},
    {"id": "f34", "area": "Day7 澀谷/原宿", "category": "鬆餅", "name": "幸せのパンケーキ表參道店", "desc": "舒芙蕾鬆餅代表店"},
    {"id": "f35", "area": "Day7 澀谷/原宿", "category": "鬆餅", "name": "gram 原宿店", "desc": ""},
    {"id": "f36", "area": "Day8 上野", "category": "豬排", "name": "とん八亭", "desc": "Tabelog百名店，只中午營業，已排入Day8午餐"},
    {"id": "f37", "area": "東京其他/通用", "category": "拉麵", "name": "金色不如歸 新宿御苑本店", "desc": "米其林一星，真鯛+蛤蜊高湯"},
    {"id": "f38", "area": "東京其他/通用", "category": "天婦羅", "name": "光村（虎之門）", "desc": "天婦羅丼飯，Tabelog高分"},
]

# 景點候選（可投票，尚未排入固定日期）
ATTRACTION_CANDIDATES = [
    {"id": "a01", "area": "原宿慢步候選", "category": "公園", "name": "代代木公園", "desc": "明治神宮出口就到，腹地大，適合休息"},
    {"id": "a02", "area": "原宿慢步候選", "category": "神社", "name": "東郷神社", "desc": "有神苑テラス庭園咖啡座，人少安靜"},
    {"id": "a03", "area": "原宿慢步候選", "category": "美術館", "name": "太田記念美術館", "desc": "浮世繪版畫美術館，室內安靜"},
    {"id": "a04", "area": "原宿慢步候選", "category": "美術館", "name": "岡本太郎記念館", "desc": "藝術家舊居工作室，冷門有特色"},
    {"id": "a05", "area": "原宿慢步候選", "category": "巷弄", "name": "キャットストリート", "desc": "原宿到表參道間安靜巷弄，設計師小店"},
    {"id": "a06", "area": "原宿逛街候選", "category": "神社", "name": "明治神宮", "desc": "尚未排入日期"},
    {"id": "a07", "area": "原宿逛街候選", "category": "商圈", "name": "竹下通", "desc": "原宿年輕人商店街，350公尺"},
    {"id": "a08", "area": "原宿逛街候選", "category": "商圈", "name": "表參道", "desc": "時尚精品大道"},
    {"id": "a09", "area": "備案", "category": "展望", "name": "東京鐵塔", "desc": "與Shibuya Sky同類型，不建議排同一天"},
    {"id": "a10", "area": "Day8候選", "category": "主題樂園", "name": "台場", "desc": "彩虹大橋、樂高樂園、DiverCity、鋼彈"},
    {"id": "a11", "area": "Day8候選", "category": "購物", "name": "銀座", "desc": "購物地標，週日有步行者天國封街"},
    {"id": "a12", "area": "Day8候選", "category": "展望", "name": "六本木", "desc": "六本木之丘、森美術館"},
    {"id": "a13", "area": "Day8候選", "category": "水族館", "name": "池袋陽光水族館", "desc": "都市高樓水族館，企鵝天空之旅"},
    {"id": "a14", "area": "Day8候選", "category": "動物園", "name": "上野動物園", "desc": "400多種動物，⚠️公休週一"},
    {"id": "a15", "area": "Day5延伸候選", "category": "水上活動", "name": "隅田川水上巴士", "desc": "淺草→台場/濱離宮，約35–40分，與合羽橋二選一"},
    {"id": "a16", "area": "Day4新宿順路候選", "category": "展望", "name": "東京都廳展望室", "desc": "免費登高看夜景/富士山，不用門票不用訂位"},
    {"id": "a17", "area": "Day4新宿順路候選", "category": "神社", "name": "花園神社", "desc": "新宿鬧區小神社，鬧中取靜"},
]

# 待辦清單，同步自 ../itinerary.md 的「待辦清單」章節
TODOS = [
    {"id": "t00", "text": "日本包車確認（1/22–1/23）——已訂美好假期，尾款¥255,000記得1/21帶現金給司機", "default_done": True},
    {"id": "t01", "text": "台灣機場接送預約（新竹團、台南團，需各約一組）", "default_done": False},
    {"id": "t02", "text": "旅平險投保", "default_done": False},
    {"id": "t03", "text": "eSIM 購買", "default_done": False},
    {"id": "t04", "text": "VJW 填寫資料", "default_done": False},
    {"id": "t05", "text": "迪士尼門票購買", "default_done": False},
    {"id": "t06", "text": "西瓜卡辦理", "default_done": False},
    {"id": "t07", "text": "行李箱確認", "default_done": False},
    {"id": "t08", "text": "豐洲市場當週公休日確認（Day7，1/27當週）", "default_done": False},
    {"id": "t09", "text": "teamLab Planets TOKYO 門票預訂（Day7，建議選較早時段）", "default_done": False},
    {"id": "t10", "text": "アキバフクロウ 貓頭鷹咖啡廳線上預約（Day4）", "default_done": False},
    {"id": "t11", "text": "紅鶴舒芙蕾鬆餅是否早起排整理券（與Day5晚出發衝突）", "default_done": False},
    {"id": "t12", "text": "Shibuya Sky 訂票（2026/12/30 東京時間00:00 開放1/27場次）", "default_done": False},
    {"id": "t13", "text": "新宿午餐店家挑選（Day4，候選已列出，需最終決定+訂位）", "default_done": False},
    {"id": "t14", "text": "合羽橋道具街 vs 隅田川水上巴士 二選一（Day5）", "default_done": False},
    {"id": "t15", "text": "明治神宮/原宿路線安插到哪一天（目前沒排進九天行程）", "default_done": False},
]
